version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: base
      POSTGRES_PASSWORD: base
      POSTGRES_DB: base
    ports:
      - 5454:5432
  base:
    depends_on: [db]
    build: .
    volumes:
      - .:/usr/app
    ports:
      - 3333:3333
